#!/usr/bin/env bash

declare -a arr=("ActiveUsers" "ARPStatus" "ConnectionsAccepted" "CPUUsage" "CryptoEngineStatus" "DateTimeStatus" "DNSCacheHostStatus" "DNSNameServerStatus" "DNSSearchDomainStatus" "DNSStaticHostStatus" "DocumentCachingSummary" "DocumentStatus" "DocumentStatusSimpleIndex" "DomainStatus" "DynamicQueueManager" "EnvironmentalFanSensors" "EnvironmentalSensors" "EthernetInterfaceStatus" "FilePollerStatus" "FilesystemStatus" "FirmwareStatus" "FirmwareVersion" "HSMKeyStatus" "HTTPConnections" "HTTPConnectionsCreated" "HTTPConnectionsDestroyed" "HTTPConnectionsOffered" "HTTPConnectionsRequested" "HTTPConnectionsReturned" "HTTPConnectionsReused" "HTTPMeanTransactionTime" "HTTPTransactions" "LibraryVersion" "LicenseStatus" "LoadBalancerStatus" "LogTargetStatus" "MemoryStatus" "MessageCountFilters" "MessageCounts" "MessageDurationFilters" "" "MessageDurations" "MessageSources" "MQQMstatus" "MQStatus" "NFSMountStatus" "NTPRefreshStatus" "ObjectStatus" "PortStatus" "ReceiveKbpsThroughput" "ReceivePacketThroughput" "RoutingStatus" "ServicesStatus" "SLMPeeringStatus" "SLMSummaryStatus" "SNMPStatus" "SSHTrustedHostStatus" "StandbyStatus" "StylesheetCachingSummary" "StylesheetExecutions" "StylesheetExecutionsSimpleIndex" "StylesheetMeanExecutionTime" "StylesheetMeanExecutionTimeSimpleIndex" "StylesheetProfiles" "StylesheetProfilesSimpleIndex" "StylesheetStatus" "StylesheetStatusSimpleIndex" "SystemUsage" "TCPSummary" "TCPTable" "TibcoEMSStatus" "TransmitKbpsThroughput" "TransmitPacketThroughput" "UDDISubscriptionKeyStatusSimpleIndex" "UDDISubscriptionServiceStatusSimpleIndex" "UDDISubscriptionStatusSimpleIndex" "Version" "WebAppFwAccepted" "WebAppFwRejected" "WebSphereJMSStatus" "WSMAgentSpoolers" "WSMAgentStatus" "WSOperationMetrics" "WSOperationsStatus" "WSRRSubscriptionServiceStatus" "WSRRSubscriptionStatus" "WSWSDLStatus" "WSWSDLStatusSimpleIndex")

for i in "${arr[@]}"
do
    curl -i -k -u user:password \
       -d "<SOAP-ENV:Envelope xmlns:SOAP-ENV=\"http://schemas.xmlsoap.org/soap/envelope/\"><SOAP-ENV:Header/><SOAP-ENV:Body xmlns:dp=\"http://www.datapower.com/schemas/management\"><dp:request domain=\"default\"><dp:get-status class=\"${i}\"/></dp:request></SOAP-ENV:Body></SOAP-ENV:Envelope>" \
       https://localhost:5550/service/mgmt/current
done
