### ANY CHANGES TO THIS FILE DOES NOT REQUIRE A RESTART ###

#This will create this metric in all the tiers, under this path
#metricPrefix: Custom Metrics|DataPower

#This will create it in specific Tier. Replace <TIER_NAME>
metricPrefix: Server|Component:<TIER_NAME>|Custom Metrics|DataPower

servers:
  - uri: http://localhost:5550/service/mgmt/current
    displayName: server1
    username: user
    password: welcome
    domains:
      - default
      - domain1
    useBulkApi: true

  - uri: https://someotherhost:5550/service/mgmt/current
    displayName: server2
    username: user
    passwordEncrypted: C043Fag+LKEZM0AQTWPy2g==
    domainsRegex:
      - fin_domain.*
      - .*security.*
    useBulkApi: true

# number of concurrent tasks
numberOfThreads: 5


connection:
  socketTimeout: 2000
  connectTimeout: 2000
  sslCertCheckEnabled: false
  sslVerifyHostname: false
  sslProtocols: ["TLSv1"]

controllerInfo:
  controllerHost: "controller"
  controllerPort: 8080
  account: "customer1"
  username: ""
  password: ""
  encryptedPassword: ""
  encryptionKey: ""
  controllerSslEnabled: false
  enableOrchestration: false
  uniqueHostId: ""
  accountAccessKey: ""
  machinePath: ""
  simEnabled: true
  applicationName: ""
  tierName: ""
  nodeName: ""
encryptionKey: welcome

#proxy:
#  uri: http://localhost:9090
#  username: proxyyuser
#  password: proxypassword

#taskSchedule:
#  numberOfThreads: 1
#  taskDelaySeconds: 300
